import type { Metadata } from 'next';
import { Playfair_Display, Poppins } from 'next/font/google';
import './globals.css';
import { LanguageProvider } from '@/context/LanguageContext';

const geistMono = Playfair_Display({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400'],
});

const poppins = Poppins({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  params: Promise<{ lang: 'en-US' | 'de' }>;
  children: React.ReactNode;
}>) {
  return (
    <html lang={(await params).lang}>
      <LanguageProvider>
        <body
          className={`${geistMono.className} ${poppins.className}  antialiased`}
        >
          {children}
        </body>
      </LanguageProvider>
    </html>
  );
}
