import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import { LanguageProvider } from '@/context/LanguageContext';

const poppins = Lexend({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  params: Promise<{ lang: 'en-US' | 'de' }>;
  children: React.ReactNode;
}>) {
  return (
    <html lang={(await params).lang}>
      <LanguageProvider>
        <body className={`${poppins.className}`}>{children}</body>
      </LanguageProvider>
    </html>
  );
}
